### ISSUE TITLE
Must-c EN-DE dataset not found

### ISSUE THREAD

**Issue by EyjafjalIa** [bzhangGo/sltunet#4]
Hi,
Thanks for open-sourcing your code. I try to use link [FBK](https://ict.fbk.eu/must-c/) given on example Step 1. Download and Preprocess Dataset to download Must-c dataset, but the link change to https://www.fbk.eu/en/research-centers/ when I click. Do you have Must-c dataset from other platform? Thanks!

**Comment by bzhangGo** [comment]
Hey, it seems that the original FBK link was broken. If you just need the textual translation of mustc, you can check out the huggingface datasets, e.g. https://huggingface.co/datasets/enimai/MuST-C-de

**Comment by EyjafjalIa** [comment]
Thanks a lot! I have found Must-c dataset on [huggingface](https://huggingface.co/datasets/enimai/MuST-C-de) and noticed that the dataset is csv files. Could you give structure of the Must-c dataset on FBK before? So that I can check whether the [preprocess_phoneix.sh](https://github.com/bzhangGo/sltunet/tree/master/example/preprocess_phoenix.sh) work.

**Comment by bzhangGo** [comment]
they are in a different format. In mustc, textual data is organised in plain text with two files: `train.en` and `train.de`. each line in the file contains one sentence, and sentences at the same line are translations to each other. You can split the data in csv to plain text.

**Comment by EyjafjalIa** [comment]
I got it! Thank you again!

**Comment by hoaitam79** [comment]
excuse me, do you have  Must-c dataset that have mp4 files, I want to have this dataset to deal with speech to text
