### ISSUE TITLE
Training configs

### ISSUE THREAD

**Issue by ZechengLi19** [bzhangGo/sltunet#7]
Thanks for your awesome work!

I want to reproduce your work from scratch, but I found that the VAC config for CSL-Daliy and DGS-T datasets is missing. 

Could you provide it to me? This is of great significance to promote the application of DGS-T dataset.

**Comment by bzhangGo** [comment]
Hey @ZechengLi19, we used the same set of [hyperaprameters](https://github.com/bzhangGo/sltunet/blob/master/smkd/configs/phoenix14.yaml) for CSL-Daily and DGS-T.

**Comment by ZechengLi19** [comment]
Hey @bzhangGo, I got it. Thanks for your reply~
